<MyRoot>:

    random_label: random_label

    BoxLayout:
        orientation: "vertical"
        Label:
            text: "I love you!"
            text: "You are the best!"
            font_size: 64
            color: 0.85, 0.4, 1
        Label:
            id: random_label
            text: "-"
            font_size: 64
        Button:
            text: "Generate Me"
            font_size: 32
            size: 100, 50
            on_press: root.generate_number()
